# 此流水线为 gitcode.net 专用

stages:
  - murphysec
  - package
  # 使用 shell 执行器
  - shell-package
  - shell-service
  # 使用 docker 执行器
  - docker-package

# murphysec
murphysec:
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  stage: package
  # Docker 镜像开源地址：https://gitee.com/xuxiaowei-com-cn/murphysec
  image: xuxiaoweicomcn/murphysec:v3.0.1-maven-3.6.3-openjdk-17
  script:
    # murphysec 文档：https://www.murphysec.com/docs/guides/scan-scene/cli.html
    - murphysec -v
    - murphysec auth login $murphysec_token
    - murphysec scan . --log-level info --write-log-to murphysec.log --json --task-id $task_id
  artifacts:
    name: murphysec
    paths:
      - murphysec.log
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行
    - if: $CI_COMMIT_BRANCH == "main"

#
# package
package:
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  stage: package
  image: maven:3.6.3-openjdk-17
  script:
    # - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    # - GPG_FILE=/builds/xuxiaowei-cloud/xuxiaowei-cloud-next.tmp/xuxiaowei_0x97A36125_SECRET
    # - echo $GPG_FILE
    # - gpg --import $GPG_FILE
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 常量网址（极狐GitLab中文文档）：https://docs.gitlab.cn/jh/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 分支上存在的上一个最新提交：$CI_COMMIT_BEFORE_SHA
    - echo 分支上存在的上一个最新提交前八个字符：$CI_COMMIT_SHORT_SHA
    - echo ISO8601格式的提交时间戳：$CI_COMMIT_TIMESTAMP
    - echo "Name<email>格式提交的作者：$CI_COMMIT_AUTHOR"
    - echo 提交标记名称。仅在标签的管道中可用：$CI_COMMIT_TAG
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - echo 单个执行器中构建执行的唯一ID：$CI_CONCURRENT_ID
    - echo 单个执行器和项目中构建执行的唯一ID：$CI_CONCURRENT_PROJECT_ID
    - echo 作业是否手动启动：$CI_JOB_MANUAL
    - echo 作业的名称：$CI_JOB_NAME
    - echo 作业阶段的名称：$CI_JOB_STAGE
    - echo 作业开始时的UTC日期时间，采用ISO8601格式：$CI_JOB_STARTED_AT
    - echo 创建管道时的UTC日期时间，采用ISO8601格式：$CI_PIPELINE_CREATED_AT
    - echo 当前项目的ID，此ID在GitLab实例上的所有项目中都是唯一的：$CI_PROJECT_ID
    - echo 作业的项目命名空间（用户名或组名）：$CI_PROJECT_NAMESPACE
    - echo 项目目录的名称：$CI_PROJECT_NAME
    - echo 包含项目名称的项目命名空间：$CI_PROJECT_PATH
    - echo GitLab实例的主要版本：$CI_SERVER_VERSION_MAJOR
    - echo GitLab实例的次要版本：$CI_SERVER_VERSION_MINOR
    - echo GitLab实例的补丁版本：$CI_SERVER_VERSION_PATCH
    - echo GitLab实例的完整版本：$CI_SERVER_VERSION
    - echo 开始作业的用户的电子邮件：$GITLAB_USER_EMAIL
    - echo 启动作业的用户的ID：$GITLAB_USER_ID
    - echo 启动作业的用户的用户名：$GITLAB_USER_LOGIN
    - echo 启动作业的用户的名称：$GITLAB_USER_NAME
    - echo 合并请求的实例级ID，这是GitLab上所有项目的唯一ID：$CI_MERGE_REQUEST_ID
    - echo 合并请求的项目级IID（内部ID），此ID对于当前项目是唯一的：$CI_MERGE_REQUEST_IID
    - echo 合并请求的目标分支名称：$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo 作业详细信息URL：$CI_JOB_URL
    - echo 作业的内部ID，在GitLab实例中的所有作业中是唯一的：$CI_JOB_ID
    - echo 正在使用的Runner的唯一ID：$CI_RUNNER_ID
    - echo 运行作业的GitLabRunner的版本：$CI_RUNNER_VERSION
    - echo 管道详细信息的URL：$CI_PIPELINE_URL
    - echo 当前管道的实例级ID。此ID在GitLab实例上的所有项目中都是唯一的：$CI_PIPELINE_ID
    - echo 当前管道的项目级IID（内部ID），此ID仅在当前项目中是唯一的：$CI_PIPELINE_IID
    - echo GitLab实例URL的主机，没有协议或端口：$CI_SERVER_HOST
    - echo 项目的HTTP（S）地址：$CI_PROJECT_URL
    - echo 克隆Git存储库的URL：$CI_REPOSITORY_URL
    # 配置 Maven 仓库的密码，用于上传 Maven
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>\n&#" settings.xml
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>\n&#" settings-private.xml
    - mvn clean -e -U package source:jar javadoc:jar install -DskipTests -s settings.xml && PACKAGE_FLAG=1
    - if [ "$PACKAGE_FLAG" == "1" ]; then echo '打包完成'; else echo '打包失败' && xxxx; fi
  # 产物超过 1000M，取消产物上传，节省时间
  #  artifacts:
  #    name: package
  #    paths:
  #      - target/*.jar
  #      - target/*.asc
  #      - target/*.pom
  #      - "*/target/*.jar"
  #      - "*/target/*.asc"
  #      - "*/target/*.pom"
  #      - "*/*/target/*.jar"
  #      - "*/*/target/*.asc"
  #      - "*/*/target/*.pom"
  #      - ui/dist
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行
    - if: $CI_COMMIT_BRANCH == "main"

#
# 使用 shell 执行器 打包
shell-package:
  stage: shell-package
  script:
    # 只能导入一次，否则会报错（开发者自己导入，或者不使用 gpg）
    # - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    # - echo $GPG_FILE
    # - gpg --import $GPG_FILE
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 常量网址（极狐GitLab中文文档）：https://docs.gitlab.cn/jh/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    # 在 Shell 执行器中，如果手动导入 gpg，可使用参数 -Pgpg
    # 在 Shell 执行器中，不指定 settings.xml，可使用系统默认
    - mvn clean -e -U package source:jar javadoc:jar install -DskipTests -s settings.xml && PACKAGE_FLAG=1
    - if [ "$PACKAGE_FLAG" == "1" ]; then echo '打包完成'; else echo '打包失败' && xxxx; fi
  artifacts:
    name: package
    paths:
      - target/*.jar
      - target/*.asc
      - target/*.pom
      - "*/target/*.jar"
      - "*/target/*.asc"
      - "*/target/*.pom"
      - "*/*/target/*.jar"
      - "*/*/target/*.asc"
      - "*/*/target/*.pom"
      - ui/dist
  rules:
    # 仅在 shell 分支中执行
    # 此处禁用 gitcode.net 上的流水线，仅在个人搭建的 gitlab 上运行
    - if: $CI_COMMIT_BRANCH == "shell" && $CI_SERVER_HOST != 'gitcode.net'
  tags:
    # 仅在 tags 名称为 shell 的执行器上执行
    - shell

#
# 使用 docker 执行器 打包
docker-package:
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  stage: docker-package
  image: maven:3.6.3-openjdk-17
  script:
    # - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    # - GPG_FILE=/builds/xuxiaowei-cloud/xuxiaowei-cloud-next.tmp/xuxiaowei_0x97A36125_SECRET
    # - echo $GPG_FILE
    # - gpg --import $GPG_FILE
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 常量网址（极狐GitLab中文文档）：https://docs.gitlab.cn/jh/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    # 配置 Maven 仓库的密码，用于上传 Maven
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>\n&#" settings.xml
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>\n&#" settings-private.xml
    - mvn clean -e -U package source:jar javadoc:jar install -DskipTests -s settings.xml && PACKAGE_FLAG=1
    - if [ "$PACKAGE_FLAG" == "1" ]; then echo '打包完成'; else echo '打包失败' && xxxx; fi
  cache:
    paths:
      - .m2/repository
      - passport-ui/node/
      - passport-ui/node_modules/
      - ui/node/
      - ui/node_modules/
  artifacts:
    name: package
    paths:
      - target/*.jar
      - target/*.asc
      - target/*.pom
      - "*/target/*.jar"
      - "*/target/*.asc"
      - "*/target/*.pom"
      - "*/*/target/*.jar"
      - "*/*/target/*.asc"
      - "*/*/target/*.pom"
      - ui/dist
  rules:
    # 仅在 docker 分支中执行
    # 此处禁用 gitcode.net 上的流水线，仅在个人搭建的 gitlab 上运行
    - if: $CI_COMMIT_BRANCH == "docker" && $CI_SERVER_HOST != 'gitcode.net'
  tags:
    # 仅在 tags 名称为 docker 的执行器上执行
    - docker

# 嵌入
include:
  # 对象储存
  # 已禁用，有需要时才开放此内容
  # - /upload.yml
  # 使用 shell 执行器 部署服务
  - /shell-service.yml
